//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GymManagementEntities : DbContext
    {
        public GymManagementEntities()
            : base("name=GymManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administratorzy> Administratorzy { get; set; }
        public virtual DbSet<Dietetycy> Dietetycy { get; set; }
        public virtual DbSet<Diety> Diety { get; set; }
        public virtual DbSet<Karnety> Karnety { get; set; }
        public virtual DbSet<Klienci> Klienci { get; set; }
        public virtual DbSet<PracownicyKasowi> PracownicyKasowi { get; set; }
        public virtual DbSet<Produkty> Produkty { get; set; }
        public virtual DbSet<PrzypisaneDiety> PrzypisaneDiety { get; set; }
        public virtual DbSet<Silownie> Silownie { get; set; }
        public virtual DbSet<Sprzety> Sprzety { get; set; }
        public virtual DbSet<Transakcje> Transakcje { get; set; }
        public virtual DbSet<Trenerzy> Trenerzy { get; set; }
        public virtual DbSet<Treningi> Treningi { get; set; }
        public virtual DbSet<Uzytkownicy> Uzytkownicy { get; set; }
        public virtual DbSet<WypozyczeniaSprzetu> WypozyczeniaSprzetu { get; set; }
        public virtual DbSet<ZarezerwowaneTreningi> ZarezerwowaneTreningi { get; set; }
    }
}
