//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymManagement
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class WypozyczeniaSprzetu
    {
        public int idWypo { get; set; }
        public int idSprzet { get; set; }
        public int idKlient { get; set; }
        public System.DateTime data { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual Sprzety Sprzety { get; set; }
    }
}
